### PR TITLE
AG-227 - Make RecoveryXAResource reconnectable

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by barreiro** [comment]
@graben this is great! 

we need to have a test case as well. I have yet been able to come up with a scenario where the `RecoveryManager` triggers the issue.

**Comment by graben** [comment]
@barreiro : Do you have something to share?

**Comment by graben** [comment]
@barreiro: Maybe I'll find a solution, let me think about it...

**Comment by barreiro** [comment]
@graben I have something using a custom `RecoveryModule` for testing purposes. I'm unsure if that mimics the actual issue, but at least it can make possible to test what we think that may be happening.

**Comment by graben** [comment]
@barreiro : Well, I asked your colleague for more details. Hope it would help to define a test case.

**Comment by graben** [comment]
@barreiro : Lets's go with your test case.

**Pull request merged**
