### PR TITLE
Bump Narayana to version 5.10.5.Final

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by barreiro** [comment]
thanks @oscerd !
Is there any particular issue this update addresses !?

**Comment by oscerd** [comment]
Hello @barreiro no, nothing special. Quarkus just updated to that version, that's why I was upgrading here too.

**Comment by jesperpedersen** [comment]
+0

**Comment by oscerd** [comment]
It seems there is no interest in upgrading, so closing this.

**Pull request closed without merging**
