### PR TITLE
AG-215: Fix SpringBoot related configuration bug and add spring to surefire groups

### PR DESCRIPTION
**Pull request by graben**
Ready once narayana-spring-boot 3.0.0 is released. (snowdrop/narayana-spring-boot#105) Actually, a SNAPSHOT version of narayana-spring-boot-starter is needed to run. Therefor, actions are currently failing!

### CODE REVIEW

**Comment by barreiro** [comment]
@graben what is the status of this PR ??

**Comment by graben** [comment]
Still waiting for the 3.0.0 release of narayana-spring-boot. It's quite hard to keep this project going at the moment :'(

**Comment by graben** [comment]
@barreiro : We are ready! :-)

**Review by barreiro — APPROVED** [review]

**Comment by barreiro** [comment]
@graben awesome!

**Pull request merged**
